import uscisEnglish from './uscisEnglish.json'
import uscisZomi from './uscisZomi.json'
import uscisEnglishTest from './uscisEnglishTest.json'
import uscisZomiTest from './uscisZomiTest.json'

export const listOfEnglish = [uscisEnglish.N1, uscisEnglish.N2, uscisEnglish.N3, uscisEnglish.N4, uscisEnglish.N5,
                              uscisEnglish.N6, uscisEnglish.N7, uscisEnglish.N8, uscisEnglish.N9, uscisEnglish.N10,
                              uscisEnglish.N11, uscisEnglish.N12, uscisEnglish.N13, uscisEnglish.N14, uscisEnglish.N15,
                              uscisEnglish.N16, uscisEnglish.N17, uscisEnglish.N18, uscisEnglish.N19, uscisEnglish.N20,
                              uscisEnglish.N21, uscisEnglish.N22, uscisEnglish.N23, uscisEnglish.N24, uscisEnglish.N25,
                              uscisEnglish.N26, uscisEnglish.N27, uscisEnglish.N28, uscisEnglish.N29, uscisEnglish.N30,
                              uscisEnglish.N31, uscisEnglish.N32, uscisEnglish.N33, uscisEnglish.N34, uscisEnglish.N35,
                              uscisEnglish.N36, uscisEnglish.N37, uscisEnglish.N38, uscisEnglish.N39, uscisEnglish.N40,
                              uscisEnglish.N41, uscisEnglish.N42, uscisEnglish.N43, uscisEnglish.N44, uscisEnglish.N45,
                              uscisEnglish.N46, uscisEnglish.N47, uscisEnglish.N48, uscisEnglish.N49, uscisEnglish.N50,
                              uscisEnglish.N51, uscisEnglish.N52, uscisEnglish.N53, uscisEnglish.N54, uscisEnglish.N55,
                              uscisEnglish.N66, uscisEnglish.N57, uscisEnglish.N58, uscisEnglish.N59, uscisEnglish.N60,
                              uscisEnglish.N61, uscisEnglish.N62, uscisEnglish.N63, uscisEnglish.N64, uscisEnglish.N65,
                              uscisEnglish.N66, uscisEnglish.N67, uscisEnglish.N68, uscisEnglish.N69, uscisEnglish.N70,
                              uscisEnglish.N71, uscisEnglish.N72, uscisEnglish.N73, uscisEnglish.N74, uscisEnglish.N75,
                              uscisEnglish.N76, uscisEnglish.N77, uscisEnglish.N78, uscisEnglish.N79, uscisEnglish.N80,
                              uscisEnglish.N81, uscisEnglish.N82, uscisEnglish.N83, uscisEnglish.N84, uscisEnglish.N85,
                              uscisEnglish.N86, uscisEnglish.N87, uscisEnglish.N88, uscisEnglish.N89, uscisEnglish.N90,
                              uscisEnglish.N91, uscisEnglish.N92, uscisEnglish.N93, uscisEnglish.N94, uscisEnglish.N95,
                              uscisEnglish.N96, uscisEnglish.N97, uscisEnglish.N98, uscisEnglish.N99, uscisEnglish.N100]

export const listOfZomi =   [ uscisZomi.N1, uscisZomi.N2, uscisZomi.N3, uscisZomi.N4, uscisZomi.N5,
                              uscisZomi.N6, uscisZomi.N7, uscisZomi.N8, uscisZomi.N9, uscisZomi.N10,
                              uscisZomi.N11, uscisZomi.N12, uscisZomi.N13, uscisZomi.N14, uscisZomi.N15,
                              uscisZomi.N16, uscisZomi.N17, uscisZomi.N18, uscisZomi.N19, uscisZomi.N20,
                              uscisZomi.N21, uscisZomi.N22, uscisZomi.N23, uscisZomi.N24, uscisZomi.N25,
                              uscisZomi.N26, uscisZomi.N27, uscisZomi.N28, uscisZomi.N29, uscisZomi.N30,
                              uscisZomi.N31, uscisZomi.N32, uscisZomi.N33, uscisZomi.N34, uscisZomi.N35,
                              uscisZomi.N36, uscisZomi.N37, uscisZomi.N38, uscisZomi.N39, uscisZomi.N40,
                              uscisZomi.N41, uscisZomi.N42, uscisZomi.N43, uscisZomi.N44, uscisZomi.N45,
                              uscisZomi.N46, uscisZomi.N47, uscisZomi.N48, uscisZomi.N49, uscisZomi.N50,
                              uscisZomi.N51, uscisZomi.N52, uscisZomi.N53, uscisZomi.N54, uscisZomi.N55,
                              uscisZomi.N66, uscisZomi.N57, uscisZomi.N58, uscisZomi.N59, uscisZomi.N60,
                              uscisZomi.N61, uscisZomi.N62, uscisZomi.N63, uscisZomi.N64, uscisZomi.N65,
                              uscisZomi.N66, uscisZomi.N67, uscisZomi.N68, uscisZomi.N69, uscisZomi.N70,
                              uscisZomi.N71, uscisZomi.N72, uscisZomi.N73, uscisZomi.N74, uscisZomi.N75,
                              uscisZomi.N76, uscisZomi.N77, uscisZomi.N78, uscisZomi.N79, uscisZomi.N80,
                              uscisZomi.N81, uscisZomi.N82, uscisZomi.N83, uscisZomi.N84, uscisZomi.N85,
                              uscisZomi.N86, uscisZomi.N87, uscisZomi.N88, uscisZomi.N89, uscisZomi.N90,
                              uscisZomi.N91, uscisZomi.N92, uscisZomi.N93, uscisZomi.N94, uscisZomi.N95,
                              uscisZomi.N96, uscisZomi.N97, uscisZomi.N98, uscisZomi.N99, uscisZomi.N100]

export const listOfEnglishTest =  [ uscisEnglishTest.N1, uscisEnglishTest.N2, uscisEnglishTest.N3, uscisEnglishTest.N4, uscisEnglishTest.N5,
                                    uscisEnglishTest.N6, uscisEnglishTest.N7, uscisEnglishTest.N8, uscisEnglishTest.N9, uscisEnglishTest.N10,
                                    uscisEnglishTest.N11, uscisEnglishTest.N12, uscisEnglishTest.N13, uscisEnglishTest.N14, uscisEnglishTest.N15,
                                    uscisEnglishTest.N16, uscisEnglishTest.N17, uscisEnglishTest.N18, uscisEnglishTest.N19, uscisEnglishTest.N20,
                                    uscisEnglishTest.N21, uscisEnglishTest.N22, uscisEnglishTest.N23, uscisEnglishTest.N24, uscisEnglishTest.N25,
                                    uscisEnglishTest.N26, uscisEnglishTest.N27, uscisEnglishTest.N28, uscisEnglishTest.N29, uscisEnglishTest.N30,
                                    uscisEnglishTest.N31, uscisEnglishTest.N32, uscisEnglishTest.N33, uscisEnglishTest.N34, uscisEnglishTest.N35,
                                    uscisEnglishTest.N36, uscisEnglishTest.N37, uscisEnglishTest.N38, uscisEnglishTest.N39, uscisEnglishTest.N40,
                                    uscisEnglishTest.N41, uscisEnglishTest.N42, uscisEnglishTest.N43, uscisEnglishTest.N44, uscisEnglishTest.N45,
                                    uscisEnglishTest.N46, uscisEnglishTest.N47, uscisEnglishTest.N48, uscisEnglishTest.N49, uscisEnglishTest.N50,
                                    uscisEnglishTest.N51, uscisEnglishTest.N52, uscisEnglishTest.N53, uscisEnglishTest.N54, uscisEnglishTest.N55,
                                    uscisEnglishTest.N66, uscisEnglishTest.N57, uscisEnglishTest.N58, uscisEnglishTest.N59, uscisEnglishTest.N60,
                                    uscisEnglishTest.N61, uscisEnglishTest.N62, uscisEnglishTest.N63, uscisEnglishTest.N64, uscisEnglishTest.N65,
                                    uscisEnglishTest.N66, uscisEnglishTest.N67, uscisEnglishTest.N68, uscisEnglishTest.N69, uscisEnglishTest.N70,
                                    uscisEnglishTest.N71, uscisEnglishTest.N72, uscisEnglishTest.N73, uscisEnglishTest.N74, uscisEnglishTest.N75,
                                    uscisEnglishTest.N76, uscisEnglishTest.N77, uscisEnglishTest.N78, uscisEnglishTest.N79, uscisEnglishTest.N80,
                                    uscisEnglishTest.N81, uscisEnglishTest.N82, uscisEnglishTest.N83, uscisEnglishTest.N84, uscisEnglishTest.N85,
                                    uscisEnglishTest.N86, uscisEnglishTest.N87, uscisEnglishTest.N88, uscisEnglishTest.N89, uscisEnglishTest.N90,
                                    uscisEnglishTest.N91, uscisEnglishTest.N92, uscisEnglishTest.N93, uscisEnglishTest.N94, uscisEnglishTest.N95,
                                    uscisEnglishTest.N96, uscisEnglishTest.N97, uscisEnglishTest.N98, uscisEnglishTest.N99, uscisEnglishTest.N100]

export const listOfZomiTest = [ uscisZomiTest.N1, uscisZomiTest.N2, uscisZomiTest.N3, uscisZomiTest.N4, uscisZomiTest.N5,
                                uscisZomiTest.N6, uscisZomiTest.N7, uscisZomiTest.N8, uscisZomiTest.N9, uscisZomiTest.N10,
                                uscisZomiTest.N11, uscisZomiTest.N12, uscisZomiTest.N13, uscisZomiTest.N14, uscisZomiTest.N15,
                                uscisZomiTest.N16, uscisZomiTest.N17, uscisZomiTest.N18, uscisZomiTest.N19, uscisZomiTest.N20,
                                uscisZomiTest.N21, uscisZomiTest.N22, uscisZomiTest.N23, uscisZomiTest.N24, uscisZomiTest.N25,
                                uscisZomiTest.N26, uscisZomiTest.N27, uscisZomiTest.N28, uscisZomiTest.N29, uscisZomiTest.N30,
                                uscisZomiTest.N31, uscisZomiTest.N32, uscisZomiTest.N33, uscisZomiTest.N34, uscisZomiTest.N35,
                                uscisZomiTest.N36, uscisZomiTest.N37, uscisZomiTest.N38, uscisZomiTest.N39, uscisZomiTest.N40,
                                uscisZomiTest.N41, uscisZomiTest.N42, uscisZomiTest.N43, uscisZomiTest.N44, uscisZomiTest.N45,
                                uscisZomiTest.N46, uscisZomiTest.N47, uscisZomiTest.N48, uscisZomiTest.N49, uscisZomiTest.N50,
                                uscisZomiTest.N51, uscisZomiTest.N52, uscisZomiTest.N53, uscisZomiTest.N54, uscisZomiTest.N55,
                                uscisZomiTest.N66, uscisZomiTest.N57, uscisZomiTest.N58, uscisZomiTest.N59, uscisZomiTest.N60,
                                uscisZomiTest.N61, uscisZomiTest.N62, uscisZomiTest.N63, uscisZomiTest.N64, uscisZomiTest.N65,
                                uscisZomiTest.N66, uscisZomiTest.N67, uscisZomiTest.N68, uscisZomiTest.N69, uscisZomiTest.N70,
                                uscisZomiTest.N71, uscisZomiTest.N72, uscisZomiTest.N73, uscisZomiTest.N74, uscisZomiTest.N75,
                                uscisZomiTest.N76, uscisZomiTest.N77, uscisZomiTest.N78, uscisZomiTest.N79, uscisZomiTest.N80,
                                uscisZomiTest.N81, uscisZomiTest.N82, uscisZomiTest.N83, uscisZomiTest.N84, uscisZomiTest.N85,
                                uscisZomiTest.N86, uscisZomiTest.N87, uscisZomiTest.N88, uscisZomiTest.N89, uscisZomiTest.N90,
                                uscisZomiTest.N91, uscisZomiTest.N92, uscisZomiTest.N93, uscisZomiTest.N94, uscisZomiTest.N95,
                                uscisZomiTest.N96, uscisZomiTest.N97, uscisZomiTest.N98, uscisZomiTest.N99, uscisZomiTest.N100]
