# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'uscis' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for uscis
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'

  target 'uscisTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'Firebase/AdMob'
  end

end
